# Generated by Django 5.2.10 on 2026-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstateAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=10)),
                ("co_ownership_charges", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
